audio:
  master_volume: 100
  tts_engine: espeak
  tts_gender: m
  tts_language: en
behaviour:
  blink: true
  caffeine: 0
  enabled: true
<<<<<<< HEAD
  gaze: false
=======
  gaze: true
>>>>>>> master
general:
  robot_name: robot
  startup_app: --None--
security:
  password: opsoro123
wireless:
  channel: 6
  password: RobotOpsoro
  ssid: OPSORO-bot
